# Generated by Django 5.2.4 on 2025-08-19 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_members', models.IntegerField(default=5)),
                ('min_members', models.IntegerField(default=3)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_squads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SquadMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('member', 'Member')], default='member', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='squads.squad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('squad', 'user')},
            },
        ),
    ]
