# Generated by Django 5.2.4 on 2025-11-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='squad_avatars/'),
        ),
    ]
