# Generated by Django 5.2.4 on 2025-11-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='image_url',
        ),
    ]
