# Generated by Django 5.2.4 on 2025-11-21 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_remove_currency_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='usercurrency',
            options={'verbose_name_plural': 'User Currencies'},
        ),
        migrations.AlterModelOptions(
            name='userpackage',
            options={'verbose_name_plural': 'User Packages'},
        ),
        migrations.RemoveField(
            model_name='package',
            name='ai_question_limit_per_day',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='userpackage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='userpackage',
            name='start_date',
        ),
        migrations.AddField(
            model_name='package',
            name='amount',
            field=models.IntegerField(default=0, help_text='Amount of currency provided by this package'),
        ),
        migrations.AddField(
            model_name='package',
            name='currency',
            field=models.ForeignKey(help_text='Currency provided by this package (e.g., Diamond, Gold)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='economy.currency'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='purchase_currency',
            field=models.ForeignKey(blank=True, help_text='Currency needed to purchase (e.g., VND for real money, Diamond for gold packages)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchasable_packages', to='economy.currency'),
        ),
        migrations.AddField(
            model_name='package',
            name='purchase_type',
            field=models.CharField(choices=[('real_money', 'Real Money (VND)'), ('currency', 'In-Game Currency')], help_text='How this package is purchased', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes from admin review', null=True),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending Review'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.IntegerField(help_text='Cost to purchase this package'),
        ),
        migrations.AlterUniqueTogether(
            name='usercurrency',
            unique_together={('user', 'currency')},
        ),
        migrations.AddIndex(
            model_name='userpackage',
            index=models.Index(fields=['user', 'status'], name='economy_use_user_id_b55151_idx'),
        ),
        migrations.AddIndex(
            model_name='userpackage',
            index=models.Index(fields=['status', '-created_at'], name='economy_use_status_fe1424_idx'),
        ),
    ]
