# Generated by Django 5.2.4 on 2025-09-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='method',
            field=models.CharField(choices=[('otp', 'OTP'), ('student_id', 'Student ID'), ('personal_id', 'Personal ID'), ('face', 'Face')], max_length=20),
        ),
    ]
