# Generated by Django 5.2.4 on 2025-11-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_refreshtoken_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refreshtoken',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userverification',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='refreshtoken',
            name='refresh_tok_user_id_a7fb02_idx',
        ),
        migrations.RemoveIndex(
            model_name='refreshtoken',
            name='refresh_tok_expires_a128d9_idx',
        ),
        migrations.AlterModelTable(
            name='refreshtoken',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userverification',
            table=None,
        ),
    ]
