# Generated by Django 5.2.4 on 2025-09-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='popularity_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
