# Generated by Django 5.2.4 on 2025-09-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_alter_question_popularity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfileattachment',
            name='file',
            field=models.FileField(max_length=255, upload_to='question_attachments/'),
        ),
    ]
