# Generated by Django 5.2.4 on 2025-09-29 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_alter_questionfileattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='verified_answer',
            field=models.ForeignKey(blank=True, help_text='The answer marked as most appropriate by the question owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_for_question', to='qa.answer'),
        ),
        migrations.DeleteModel(
            name='AnswerVerification',
        ),
    ]
