# Generated by Django 5.2.4 on 2025-11-18 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_question_verified_answer_delete_answerverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='popularity_score',
        ),
    ]
