# Generated by Django 5.2.4 on 2025-10-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_remove_quizquestion_answer_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='duration_seconds',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
    ]
