# Generated by Django 5.2.4 on 2025-10-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_quizattempt_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
