# Generated by Django 5.2.4 on 2025-10-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_quiz_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Simplified Chinese', 'Simplified Chinese'), ('Traditional Chinese', 'Traditional Chinese'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Indonesian', 'Indonesian'), ('Thai', 'Thai'), ('Vietnamese', 'Vietnamese'), ('German', 'German'), ('French', 'French'), ('Spanish', 'Spanish'), ('Portuguese', 'Portuguese'), ('Russian', 'Russian')], default='English', max_length=50),
        ),
    ]
