# Generated by Django 5.2.4 on 2025-10-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_quiz_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
