# Generated by Django 5.2.4 on 2025-11-05 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_quiz_rating'),
        ('qa', '0004_question_verified_answer_delete_answerverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='quiz',
            name='rating_count',
            field=models.IntegerField(default=0, help_text='Total number of ratings received'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='User rating for this quiz attempt (0-5)', max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from all user attempts (0.00-5.00)', max_digits=3),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['rating', '-created_at'], name='learning_qu_rating_725cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['subject', 'rating'], name='learning_qu_subject_f80aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz', 'created_at'], name='learning_qu_user_id_38b5b5_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'rating'], name='learning_qu_quiz_id_497d48_idx'),
        ),
    ]
