# Generated by Django 5.2.4 on 2025-12-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_quizattempt_options_quiz_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_avatars/'),
        ),
    ]
