# Generated by Django 5.2.4 on 2025-11-11 08:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_remove_currency_image_url'),
        ('gamification', '0001_initial'),
        ('squads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MissionRewards',
            new_name='MissionReward',
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['cycle', 'type']},
        ),
        migrations.RemoveField(
            model_name='mission',
            name='deadline',
        ),
        migrations.AddField(
            model_name='mission',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text="JSON conditions: {'min_score': 80, 'exclude_own_questions': true, 'min_rating': 4}"),
        ),
        migrations.AddField(
            model_name='mission',
            name='cycle',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('permanent', 'Permanent')], default='daily', help_text='Mission reset cycle: Daily (2 AM), Weekly (2 AM Monday), or Permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='mission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='is_random_pool',
            field=models.BooleanField(default=False, help_text='If true, this mission is part of a random selection pool'),
        ),
        migrations.AddField(
            model_name='mission',
            name='pool_size',
            field=models.IntegerField(default=3, help_text='Number of missions to randomly assign from pool (only for daily missions)'),
        ),
        migrations.AddField(
            model_name='reward',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='target_count',
            field=models.IntegerField(default=1, help_text='Number of times the action must be completed'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='type',
            field=models.CharField(choices=[('complete_quiz', 'Complete Quiz'), ('save_question', 'Save Question'), ('answer_question', 'Answer Question'), ('rate_quiz', 'Rate Quiz'), ('verify_answer', 'Verify Answer'), ('view_question', 'View Question'), ('get_verified', 'Get Verified'), ('create_quiz', 'Create Quiz'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Store tracking data: completed_quiz_ids, verifier_ids, etc.')),
                ('cycle_date', models.DateField(help_text='The date/week this mission instance is for')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to='gamification.mission')),
                ('squad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='squads.squad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cycle_date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MissionParticipation',
        ),
        migrations.AddIndex(
            model_name='usermission',
            index=models.Index(fields=['user', 'cycle_date', 'is_completed'], name='gamificatio_user_id_d3c90b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermission',
            unique_together={('mission', 'user', 'cycle_date')},
        ),
    ]
