# Generated by Django 5.2.4 on 2025-11-20 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_rename_missionrewards_missionreward_and_more'),
        ('squads', '0002_alter_squad_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['cycle', 'access_type', 'type']},
        ),
        migrations.AddField(
            model_name='mission',
            name='require_all_members',
            field=models.BooleanField(default=False, help_text='If true (squad missions), all squad members must complete their individual missions'),
        ),
        migrations.CreateModel(
            name='SquadMissionProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_date', models.DateField(help_text='The date/week this squad mission is for')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_members', models.JSONField(default=list, help_text='List of user IDs who have completed their individual missions')),
                ('rewards_distributed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_progress', to='gamification.mission')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to='squads.squad')),
            ],
            options={
                'ordering': ['-cycle_date', '-created_at'],
                'indexes': [models.Index(fields=['squad', 'cycle_date', 'is_completed'], name='gamificatio_squad_i_017680_idx')],
                'unique_together': {('squad', 'mission', 'cycle_date')},
            },
        ),
    ]
